name = "yslidscorner-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
CORS_ORIGIN = "https://yslidscorner.com,https://www.yslidscorner.com"
SUPABASE_URL = "https://TU-PROYECTO.supabase.co"
SUPABASE_ANON_KEY = "TU_ANON_KEY"
SUPABASE_SERVICE_ROLE_KEY = "TU_SERVICE_ROLE_KEY"
